# Lanti/DebianMariaDBBackup
#
# VERSION               1.0.0

FROM lemp_lanti-debian-base:latest
MAINTAINER Istvan Lantos <info@lantosistvan.com>
LABEL Description="MariaDB_Backup" Vendor="Istvan Lantos" Version="1.0"

RUN mkdir -p /var/lib/mysql

EXPOSE 22

CMD ["tail", "-f", "/dev/null"]
